package org.eclipse.jet.compiled;

import org.eclipse.jet.JET2Context;
import org.eclipse.jet.JET2Template;
import org.eclipse.jet.JET2Writer;
import org.eclipse.jet.taglib.RuntimeTagElement;
import org.eclipse.jet.taglib.TagInfo;

public class _jet_Intermediaryesql implements JET2Template {
    private static final String _jetns_c = "org.eclipse.jet.controlTags"; //$NON-NLS-1$

    public _jet_Intermediaryesql() {
        super();
    }

    private static final String NL = System.getProperty("line.separator"); //$NON-NLS-1$
    
    private static final TagInfo _td_c_if_5_1 = new TagInfo("c:if", //$NON-NLS-1$
            5, 1,
            new String[] {
                "test", //$NON-NLS-1$
            },
            new String[] {
                "boolean($root/brokerSchema)", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_if_7_1 = new TagInfo("c:if", //$NON-NLS-1$
            7, 1,
            new String[] {
                "test", //$NON-NLS-1$
            },
            new String[] {
                "string-length($root/brokerSchema) > 0", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_9_15 = new TagInfo("c:get", //$NON-NLS-1$
            9, 15,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/brokerSchema", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_12_18 = new TagInfo("c:get", //$NON-NLS-1$
            12, 18,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternName", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_12_63 = new TagInfo("c:get", //$NON-NLS-1$
            12, 63,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternVersion", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_13_23 = new TagInfo("c:get", //$NON-NLS-1$
            13, 23,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternName", //$NON-NLS-1$
            } );
    private static final TagInfo _td_c_get_14_26 = new TagInfo("c:get", //$NON-NLS-1$
            14, 26,
            new String[] {
                "select", //$NON-NLS-1$
            },
            new String[] {
                "$root/@patternVersion", //$NON-NLS-1$
            } );

    public void generate(final JET2Context context, final JET2Writer __out) {
        JET2Writer out = __out;

com.ibm.etools.mft.pattern.mbi.plugin.PatternPlugin pattern = com.ibm.etools.mft.pattern.mbi.plugin.PatternPlugin.getInstance();
com.ibm.etools.mft.pattern.mbi.mrrc.relmq.PatternMessages messages = new com.ibm.etools.mft.pattern.mbi.mrrc.relmq.PatternMessages();

        RuntimeTagElement _jettag_c_if_5_1 = context.getTagFactory().createRuntimeTag(_jetns_c, "if", "c:if", _td_c_if_5_1); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_if_5_1.setRuntimeParent(null);
        _jettag_c_if_5_1.setTagInfo(_td_c_if_5_1);
        _jettag_c_if_5_1.doStart(context, out);
        while (_jettag_c_if_5_1.okToProcessBody()) {
            // Tag exists 
            RuntimeTagElement _jettag_c_if_7_1 = context.getTagFactory().createRuntimeTag(_jetns_c, "if", "c:if", _td_c_if_7_1); //$NON-NLS-1$ //$NON-NLS-2$
            _jettag_c_if_7_1.setRuntimeParent(_jettag_c_if_5_1);
            _jettag_c_if_7_1.setTagInfo(_td_c_if_7_1);
            _jettag_c_if_7_1.doStart(context, out);
            while (_jettag_c_if_7_1.okToProcessBody()) {
                // and has a value
                out.write("BROKER SCHEMA ");  //$NON-NLS-1$        
                RuntimeTagElement _jettag_c_get_9_15 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_9_15); //$NON-NLS-1$ //$NON-NLS-2$
                _jettag_c_get_9_15.setRuntimeParent(_jettag_c_if_7_1);
                _jettag_c_get_9_15.setTagInfo(_td_c_get_9_15);
                _jettag_c_get_9_15.doStart(context, out);
                _jettag_c_get_9_15.doEnd();
                out.write(NL);         
                _jettag_c_if_7_1.handleBodyContent(out);
            }
            _jettag_c_if_7_1.doEnd();
            _jettag_c_if_5_1.handleBodyContent(out);
        }
        _jettag_c_if_5_1.doEnd();
        out.write("--  Generated by ");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_12_18 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_12_18); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_12_18.setRuntimeParent(null);
        _jettag_c_get_12_18.setTagInfo(_td_c_get_12_18);
        _jettag_c_get_12_18.doStart(context, out);
        _jettag_c_get_12_18.doEnd();
        out.write(" Version ");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_12_63 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_12_63); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_12_63.setRuntimeParent(null);
        _jettag_c_get_12_63.setTagInfo(_td_c_get_12_63);
        _jettag_c_get_12_63.doStart(context, out);
        _jettag_c_get_12_63.doEnd();
        out.write(NL);         
        out.write("--  $MQSI patternName=");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_13_23 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_13_23); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_13_23.setRuntimeParent(null);
        _jettag_c_get_13_23.setTagInfo(_td_c_get_13_23);
        _jettag_c_get_13_23.doStart(context, out);
        _jettag_c_get_13_23.doEnd();
        out.write(" MQSI$");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("--  $MQSI patternVersion=");  //$NON-NLS-1$        
        RuntimeTagElement _jettag_c_get_14_26 = context.getTagFactory().createRuntimeTag(_jetns_c, "get", "c:get", _td_c_get_14_26); //$NON-NLS-1$ //$NON-NLS-2$
        _jettag_c_get_14_26.setRuntimeParent(null);
        _jettag_c_get_14_26.setTagInfo(_td_c_get_14_26);
        _jettag_c_get_14_26.doStart(context, out);
        _jettag_c_get_14_26.doEnd();
        out.write(" MQSI$");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("DECLARE RequestLoggingOn EXTERNAL BOOLEAN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("DECLARE ResponseLoggingOn EXTERNAL BOOLEAN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("CREATE COMPUTE MODULE ExtractOriginalMQMD");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tCREATE FUNCTION Main() RETURNS BOOLEAN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tBEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- This is first compute - initialise to indicate Request Leg");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET Environment.Variables.RRMode = 'Request';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET Environment.Variables.RequestLoggingOn = RequestLoggingOn;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t    -- Check that the MQMD Header includes a REPLYTOQ");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tIF LENGTH(InputRoot.MQMD.ReplyToQ) = 0 THEN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tTHROW USER EXCEPTION SEVERITY 3 MESSAGE 2372 VALUES('");  //$NON-NLS-1$        
        out.write( pattern.getString("com.ibm.etools.mft.pattern.mbi.mrrc.relmq.esql.2") );
        out.write("');");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tEND IF;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- Copy the incoming original MQMD");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tDECLARE I INTEGER 1;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tDECLARE J INTEGER CARDINALITY(InputRoot.*[]);");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tWHILE I < J DO");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET OutputRoot.*[I] = InputRoot.*[I];");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t\tSET I = I + 1;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tEND WHILE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\t\t-- Copy MsgId to CorrelId as the Backend reply application would do");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- This enables the MQGet node in the Reply flow to retrieve the");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- corresponding store message by CorrelId even if the requestor did");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- not send the message as a MQSeries request message");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET OutputRoot.MQMD.CorrelId = InputRoot.MQMD.MsgId;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\t\t-- Note that we're not copying the message body it is not required");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- to be stored, we can retrieve the reply to queue from just the MQMD\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t    ");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t    -- Also save the broker queue manager name to an environment variable so that it can be used in the MQMD header node ");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- when sending to the provider");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET Environment.Variables.BrokerQueueManager = SQL.QueueManagerName;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tRETURN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("END MODULE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("CREATE COMPUTE MODULE Request_Initialise");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\tCREATE FUNCTION Main() RETURNS BOOLEAN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tBEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET OutputRoot = InputRoot;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET Environment.Variables.RRMode = 'Request';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tRETURN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("END MODULE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write(NL);         
        out.write("CREATE COMPUTE MODULE SetReplyTo");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\tCREATE FUNCTION Main() RETURNS BOOLEAN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tBEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET OutputRoot = InputRoot;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- Specify the reply-to queue in the request set to the Backend");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- reply application to be the input queue of the reply flow");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- SET OutputRoot.MQMD.ReplyToQ = '<attr node=\"entry/target/response\" name=\"queueName\"/>';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET OutputRoot.MQMD.ReplyToQ = 'MRRC.GETRESPONSE.IN';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- Queue Manager for reply is broker queue manager");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET OutputRoot.MQMD.ReplyToQMgr = SQL.QueueManagerName;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- SET Request mode so logging checks are applied correctly");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\t\tSET OutputRoot.MQMD.Expiry = -1;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tRETURN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("END MODULE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("CREATE COMPUTE MODULE HandleMQGetWarning");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tCREATE FUNCTION Main() RETURNS BOOLEAN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tBEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- The MQGet Node received a MQ Warning");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- The Tree will contain just a MQMD and any message content received ");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- in a BLOB, no parsing will be performed.");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- This could occur if the get options were set to accept truncated");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- messages. We have not set that option here.");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- Throw a user exception");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tDECLARE reasonStr CHAR;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET Environment.Variables.StatusCode = -3; ");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET reasonStr = '");  //$NON-NLS-1$        
        out.write( pattern.getString("com.ibm.etools.mft.pattern.mbi.mrrc.relmq.esql.4") );
        out.write("';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tTHROW USER EXCEPTION SEVERITY 3 MESSAGE 2372 VALUES(reasonStr);");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tRETURN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("END MODULE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write(NL);         
        out.write("CREATE COMPUTE MODULE HandleMissingStoredMsg");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tCREATE FUNCTION Main() RETURNS BOOLEAN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tBEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- The MQGet Node failed to get a message from the Store Queue");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\t-- Throw a user exception");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tDECLARE reasonStr CHAR;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET reasonStr = '");  //$NON-NLS-1$        
        out.write( pattern.getString("com.ibm.etools.mft.pattern.mbi.mrrc.relmq.esql.4") );
        out.write("';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tTHROW USER EXCEPTION SEVERITY 3 MESSAGE 2372 VALUES(reasonStr);");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tRETURN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("END MODULE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("CREATE COMPUTE MODULE SetResponseMode");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tCREATE FUNCTION Main() RETURNS BOOLEAN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\tBEGIN");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET Environment.Variables.RRMode = 'Response';");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tSET Environment.Variables.ResponseLoggingOn = ResponseLoggingOn;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write("\t\tRETURN TRUE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("\t\tEND;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write("END MODULE;");  //$NON-NLS-1$        
        out.write(NL);         
        out.write(NL);         
        out.write(NL);         
    }
}
